### ISSUE TITLE
Default adapters cause file saving to fail if all adapters are not setup

### ISSUE THREAD

**Issue by laxu** [nordsoftware/lumen-file-manager#1]
Commenting out S3 and Cloudinary adapters from FileManagerServiceProvider.php $defaultAdapters fixes this. Otherwise you get a League\Flysystem error where it tries to create an adapter but cannot because it doesn't have enough config data.

Fix would be to make local adapter the only default one. Now the default adapters config is merged with defined adapter config which doesn't remove the default ones if they don't exist.

**Comment by kryysler** [comment]
Issue has already been fixed commit 9c504b40227d0331d96f2138444cca4d41e0cd8a
