### ISSUE TITLE
Add support for Lumen 5.4

### ISSUE THREAD

**Issue by jukump** [nordsoftware/lumen-file-manager#7]
This module should be made compatible with Lumen 5.4.

For example on line https://github.com/nordsoftware/lumen-file-manager/blob/develop/src/FileManagerServiceProvider.php#L91 `$container->make` is given 2 arguments but in Lumen 5.4 the method only accepts 1. This results in
```php
Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class Nord\\Lumen\\FileManager\\Adapters\\DiskAdapter
```
This is documented in https://laravel.com/docs/5.4/upgrade under "make Method Parameters".

There might be other things to update too.

**Comment by Jalle19** [comment]
@soderluk is this still an issue?

**Comment by soderluk** [comment]
Shouldn't be. This is in use in 5.4 projects. I'll close this one.
