### ISSUE TITLE
Support for S3 Pre-Signed URL

### ISSUE THREAD

**Issue by soderluk** [nordsoftware/lumen-file-manager#8]
Add support for getting a file's pre-signed URL to S3:
https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-url.html

Should be applied to the S3Adapter.

**Comment by Jalle19** [comment]
Apparently fixed in https://github.com/digiaonline/lumen-file-manager/commit/0550d0b1f4c706678f391615971690d6bc756b0f
